# -*- coding: utf-8 -*-
"""filtering_final_function_calls.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Alhi3BGYrvH4QRnpuNx4SS13dnaj6LB6
"""

from google.colab import drive
drive.mount('/content/drive')

import csv
import pandas as pd

path_function = '' #the path to the list of function calls file 
path_to_output='' #output path

df=pd.read_csv(path_function)

df

           
list_of_10_famous_tools=['optuna','hyperopt','skopt','featuretools','tpot','bayes_opt','autokeras','autosklearn','ax','snorkel']
list_of_final_final_calls=[]

filtered_final_function_call_file = open(path_to_output + 'filtered_final_function_call.csv', mode='w', newline='',encoding='utf-8')
filtered_final_function_call_writer = csv.writer(filtered_final_function_call_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
filtered_final_function_call_writer.writerow(['final_function_call'])


index=df.index
# print(index.stop)
for ind in range (index.start, index.stop-2):
  print("INDDD IS :",ind)
  if df['final_function_call'][ind].split('.')[0] in list_of_10_famous_tools:
    for ind2 in range (ind+1,index.stop-2):
      print("ind2 is:", ind2)
      print("type ind2 is :",type(ind2))
      if df['final_function_call'][ind2].split('.')[0] in list_of_10_famous_tools:
        print("type of df['final_function_call'][ind] is: ", len(df['final_function_call'][ind]))
        print("type of df['final_function_call'][ind2] is:", len(df['final_function_call'][ind2]))
        if ((df['final_function_call'][ind]) in (df['final_function_call'][ind2])):
          if len(df['final_function_call'][ind]) < len(df['final_function_call'][ind2]):
            pass
        elif (df['final_function_call'][ind] in df['final_function_call'][ind2]) and (len(df['final_function_call'][ind]) >= len(df['final_function_call'][ind2])):
          filtered_final_function_call_writer.writerow([df['final_function_call'][ind]])             

           
filtered_final_function_call_file.close()
