# -*- coding: utf-8 -*-
"""randomly pick function for fifth round of labeling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_J0gJPki794Wg3gjmXmW0ImatNQVR9OR
"""

from google.colab import drive
drive.mount('/content/drive')

import csv
import pandas as pd

path_function = '/content/drive/MyDrive/PhD/Automate machine learning/presentations for the meetings/12th meeting/dataset/functions/Fifth round of labeling - Sheet1.csv'
path_to_output='/content/drive/MyDrive/PhD/Automate machine learning/presentations for the meetings/12th meeting/dataset/functions/'

df=pd.read_csv(path_function)

df

randomly_picked_function_calls_file = open(path_to_output + 'randomly_picked_238_function_calls_for_fifth_round.csv', mode='w', newline='',encoding='utf-8')
randomly_picked_function_calls_file_writer = csv.writer(randomly_picked_function_calls_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
randomly_picked_function_calls_file_writer.writerow(['id','function_calls','fourth round stage labels','fourth round labels','Additional information'])

import random
randomlist = random.sample(range(0, 618), 238)
print(randomlist)

for i in range (len(randomlist)+1):
  randomly_picked_function_calls_file_writer.writerow([df.id[i],df.function_calls[i],df.fourth_round_stage_labels[i],df.fourth_round_labels[i],df.Additional_information[i]])

randomly_picked_function_calls_file.close()
