# -*- coding: utf-8 -*-
"""scattered plot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aq07yo91HZVu79HUEhSzKbsmkpk91qob
"""

from google.colab import drive
drive.mount('/content/drive')

import csv
import pandas as pd

path_input ="/content/drive/MyDrive/PhD/Automate machine learning/presentations for the meetings/12th meeting/dataset/functions/combined_function_calls2 - labeling 1 to 10 automl tools with shannon entrop (3).csv"
path_output= "/content/drive/MyDrive/PhD/Automate machine learning/presentations for the meetings/12th meeting/dataset/functions/filtered_final_function_call/"
filtered_final_function_call_file = open(path_output + 'combined_function_calls2 - filtered_labeling 1 to 10 automl tools with shannon entrop>80.csv', mode='w', newline='',encoding='utf-8')
filtered_final_function_call_writer = csv.writer(filtered_final_function_call_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
filtered_final_function_call_writer.writerow(['id','final_function_call','COUNTA_of_final_function_call2','shanon_entropy','new_purpose','purpose (Action)','Stage of ML pipeline','additional information'])




filtered_final_function_call_file2 = open(path_output + 'combined_function_calls2 - filtered_labeling 1 to 10 automl tools with shannon entrop_frequency8-10 and entropy 0.13-20.csv', mode='w', newline='',encoding='utf-8')
filtered_final_function_call_writer2 = csv.writer(filtered_final_function_call_file2, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
filtered_final_function_call_writer2.writerow(['id','final_function_call','COUNTA_of_final_function_call2','shanon_entropy','new_purpose','purpose (Action)','Stage of ML pipeline','additional information'])

df=pd.read_csv(path_input)
df

import matplotlib.pyplot as plt
plt.scatter(df['shanon_entropy'],df['COUNTA_of_final_function_call2'])
plt.xlim([0, 0.6])
plt.ylim([0, 300])
plt.show()

counter=0
len1=len(df.index)
print("df index:",len(df.index))
for i in range(len1):
  if (df.COUNTA_of_final_function_call2.values[i]) >10 and df.shanon_entropy.values[i] > 0.15:
    counter+=1
    filtered_final_function_call_writer.writerow([df['id'][i], df['final_function_call'][i], df['COUNTA_of_final_function_call2'][i],df['shanon_entropy'][i], df['new_purpose'][i],df['purpose (Action)'][i], df['Stage of ML pipeline'][i], df['additional information'][i]])
print("counter is:", counter)
filtered_final_function_call_file.close()



boxplot = df.boxplot(column=['COUNTA_of_final_function_call2'])

import numpy as np


print(np.percentile(df.COUNTA_of_final_function_call2,80))

import numpy as np


print(np.percentile(df.shanon_entropy, 80))
